language: go

go:
- 1.x
- "1.10"
- 1.11.x
- master

go_import_path: github.com/fx19880617/pinot-client-go

sudo: false

branches:
  only:
    - master

before_install:
  - make setup

before_script:
  - make lint

script: make
