language: go

go:
- 1.x
- master

go_import_path: github.com/startreedata/pinot-client-go

sudo: false

branches:
  only:
    - master

before_install:
  - make setup

before_script:
  - make lint

script: make
